#!/bin/bash

#This is the project directory, named Orca_Project
PRJ_DIR=$(dirname $(dirname $(realpath $0)))

do_prepare_env(){
    if ! [ -f $PRJ_DIR/orca-env/pyvenv.cfg ]
    then
        echo "Setting python's virtual environment ..."
        python3 -m venv $PRJ_DIR/orca-env || {
            echo "Error - Unable to set python's vitual environment"
            exit 1
        }
        echo "Activating python's virtual environment ..."
        source $PRJ_DIR/orca-env/bin/activate || {
            echo "Error - Unable to create python's vitual environment"
            exit 1
        }
        echo "Installing KAS in python's virtual environment ..."
        pip3 install kas || {
            echo "Error - Unable to install KAS in python's vitual environment"
            exit 1
        }
    else
        echo "Python's virtual environment already set"
        echo "Activating python's virtual environment ..."
        source $PRJ_DIR/orca-env/bin/activate || {
            echo "Error - Unable to install KAS in python's vitual environment"
            exit 1
        }
        if [ -z $(pip list | grep -o kas) ]
        then 
            echo "Installing KAS in python's virtual environment ..."
            pip install kas || {
            echo "Error - Unable to install KAS in python's vitual environment"
            exit 1
            }
        else
            echo "KAS already installed in python's virtual environment"
        fi
    fi

    sed -i '0,/PARALLEL_MAKE/ s:PARALLEL_MAKE.*:PARALLEL_MAKE = "'"-j $(( $(nproc) / 2 ))"'":' $PRJ_DIR/kas/include/local.yml
    sed -i '0,/BB_NUMBER_THREADS/ s:BB_NUMBER_THREADS.*:BB_NUMBER_THREADS = "'"-j $(( $(nproc) / 2 ))"'":' $PRJ_DIR/kas/include/local.yml

    [ -n $(sed 's/share\://' $PRJ_DIR/scripts/.info) ] || {
        local share_dir=$(dirname $PRJ_DIR)/YoctoShare
        if ! [ -d $share_dir/downloads ] || ! [ -d $share_dir/sstate-cache ]
        then 
            echo "Creating shared volume for downloads and sstate-cache..."
            mkdir -p $share_dir/downloads || {
                echo "ERROR - Could create shared downloads directory"
                exit 1
            }
            mkdir -p $share_dir/sstate-cache || {
                echo "ERROR - Could create shared sstate-cache directory"
                exit 1
            }
            echo "share:$sharedir" >> $PRJ_DIR/scripts/.info
            return 0
        else
            return 0
        fi
    }
    return 0
}

Usage(){
    echo "Usage - ./setuporca [command] [path/to/kas/.yml] OR ./setuporca prepare"
    echo "Usage - command: shell/build/checkout/clean"
}

do_check_args(){ 
    if [ $# -eq 1 ]
    then
        if [ "$1" == "prepare" ]
        then
            touch $PRJ_DIR/scripts/.info 
            return 0
        else
            echo "Error - Unexpected command that takes no arguments"
            Usage
            exit 1
        fi
    else
        if [ $# -ne 2 ] 
        then
            echo "Error - Non-compliance with usage rules"
            Usage
            exit 1
        else
            if [ "$1" == "prepare" ] 
            then
                touch $PRJ_DIR/scripts/.info
                local yshare_dir=$(realpath $2)
                if ! [ -d $yshare_dir/downloads ] || ! [ -d $yshare_dir/sstate-cache ] 
                then
                    echo "Error - Invalid share directory: path/to/share/directory/downloads and path/to/share/directory/sstate-cache must be available"
                    Usage
                    exit 1
                fi
                if [ -z $(sed 's/share\://' $PRJ_DIR/scripts/.info) ] 
                then
                    echo -n "share:$yshare_dir" >> $PRJ_DIR/scripts/.info
                else
                    sed -i "s|share.*|share:${yshare_dir}|" $PRJ_DIR/scripts/.info
                fi
                return 0
            else
                local cmd=$1
                local kas_yaml=$2
                if [ $cmd != "shell" ] && [ $cmd != "build" ] && [ $cmd != "checkout" ] && [ $cmd != "clean" ]
                then
                    echo "Error - Unknown commmand"
                    Usage 
                    exit 1
                else
                    if ! [ -f $kas_yaml ] || [[ $kas_yaml =~ *'.yml' ]]
                    then
                        echo "Error - Could not find a compliant file"
                        Usage
                        exit 1
                    fi
                fi
                return 0
            fi
        fi
    fi
}

main(){ 
    do_check_args $@
    local cmd=$1
    local kas_yaml=$2
    if [ "$cmd" == "prepare" ]
    then
        do_prepare_env
        return 0
    else
        export KAS_WORK_DIR=$PRJ_DIR
        source $PRJ_DIR/orca-env/bin/activate || {
            echo "Error - Unable to create python's vitual environment"
            exit 1
        }
        local share_dir=$(sed 's/share\://' $PRJ_DIR/scripts/.info)
        kas-container --runtime-args "-v $share_dir:/work/share/:rw" $cmd $kas_yaml || {
        echo "Error - Environment exit with error"
        exit 1 
        }
        return 0
    fi
}

main $@