header:
  version: 18

local_conf_header:
  recommendations: |
    NO_RECOMMENDATIONS = "1"

  shared: |
    SSTATE_DIR="/work/share/sstate-cache"
    DL_DIR="/work/share/downloads"

  security: |
    INHERIT += "cve-check"

  ressources: |
    PARALLEL_MAKE = "-j 8"
    PARALLEL_MAKEINST = "${PARALLEL_MAKE}"
    BB_NUMBER_THREADS = "-j 8"
    BB_NUMBER_PARSE_THREADS = "${BB_NUMBER_THREADS}"

