header:
  version: 18

local_conf_header:
  shared: |
    NO_RECOMMENDATIONS = "1"
    SSTATE_DIR="/work/share/sstate-cache"
    DL_DIR="/work/share/downloads"

  ressources: |
    PARALLEL_MAKE = "-j 10"
    BB_NUMBER_THREADS = "12"

